CSRF_ENABLED = True
SECRET_KEY = 'C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='

COSMOSDB_HOST = 'https://localhost:8081/'
COSMOSDB_KEY = 'C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='

COSMOSDB_DATABASE = 'service catalogue'
COSMOSDB_COLLECTION_VM = 'virtualmachines'
COSMOSDB_COLLECTION_VMID = 'vmid'
COSMOSDB_COLLECTION_IP = 'ipaddresses'
COSMOSDB_COLLECTION_FW = 'firewallrules'
COSMOSDB_COLLECTION_FWID = 'fwid'
COSMOSDB_COLLECTION_SUBNET = 'subnets'